# Generated by Django 5.2.6 on 2025-12-09 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="project",
            name="image_url",
        ),
        migrations.AddField(
            model_name="client",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="clients/"),
        ),
        migrations.AddField(
            model_name="project",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="projects/"),
        ),
    ]
